simplaification build.yml : ne laisser que le build et le test

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -19,25 +19,29 @@ jobs:
            - name: Setup Gradle
              uses: gradle/gradle-build-action@v2
            - name: Make gradlew executable
-             run: chmod +x ./gradlew
+             run:  chmod +x ./gradlew
            - name: Build, test and compute JaCoCo reports
              run: ./gradlew build jacocoTestReport
-           - name: Rapport de tests
-             uses: dorny/test-reporter@v1
-             if: success() || failure()
-             with:
-                 name: JUnit Tests
-                 path: build/test-results/test/TEST-*.xml
-                 reporter: java-junit
-           - name: JaCoCo Code Coverage Report
-             id: jacoco_reporter
-             uses: PavanMudigonda/jacoco-reporter@v4.8
-             with:
-                 coverage_results_path: build/reports/jacoco/test/jacocoTestReport.xml
-                 coverage_report_name: Coverage
-                 coverage_report_title: JaCoCo
-                 github_token: ${{ secrets.GITHUB_TOKEN }}
-                 skip_check_run: false
-                 minimum_coverage: 80
-                 fail_below_threshold: false
-                 publish_only_summary: false    
+#
+#
+#
+#
+#         - name: Rapport de tests
+#            uses: dorny/test-reporter@v1
+#            if: success() || failure()
+#            with:
+#                name: JUnit Tests
+#                path: build/test-results/test/TEST-*.xml
+#                reporter: java-junit
+#          - name: JaCoCo Code Coverage Report
+#            id: jacoco_reporter
+#            uses: PavanMudigonda/jacoco-reporter@v4.8
+#            with:
+#                coverage_results_path: build/reports/jacoco/test/jacocoTestReport.xml
+#                coverage_report_name: Coverage
+#                coverage_report_title: JaCoCo
+#                github_token: ${{ secrets.GITHUB_TOKEN }}
+#                skip_check_run: false
+#                minimum_coverage: 80
+#                fail_below_threshold: false
+#                publish_only_summary: false
